### ISSUE TITLE
Request as HTML

### ISSUE THREAD

**Issue by wkhatch** [afeld/jeditable-rails#8]
When following the usage doc's, the responses are coming back using html, not js. 
Per the logs:

Processing by ObservationsController#update as HTML

**Comment by afeld** [comment]
I think an HTML response is most appropriate, since the result is being displayed as HTML directly.  If you wanted to have conditional logic, you could add an `if request.xhr?` check in the controller.  If you disagree, feel free to reopen the issue with your thoughts.
